services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
  - 12
  - node

matrix:
  include:
    - name: Lint
      node_js: 14
      script: npm run lint

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
env: CXX="g++-4.8" CC="gcc-4.8"

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce1a1b401d97fe096e2
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
